### ISSUE TITLE
Unifi broker after update, mongodb issue

### ISSUE THREAD

**Issue by al13nus** [mimugmail/opn-repo#236]
Hey guys,

what can I do here? Happended after OPNSense update from 24.1.9 to 24.7.4. 
My attempts:

1. MongoDB wasn't running, so I restarted it. 
2. Tried to delete and reinstall the package.
3. Firewall restart.
4. Deleted folder of mongoDB `rm -r "/var/db/mongodb/"`

```
sudo service mongod start
Cannot 'start' mongod. Set mongod_enable to YES in /etc/rc.conf or use 'onestart' instead of 'start'.
```
Logs:
```[2024-09-22 13:00:20,893] <launcher> INFO  startup - Initiating startup
[2024-09-22 13:00:21,808] <launcher> INFO  system - ======================================================================
[2024-09-22 13:00:21,808] <launcher> INFO  system - UniFi 8.2.93 (build atag_8.2.93_25939 - release/release) is started
[2024-09-22 13:00:21,811] <launcher> INFO  system - Environment: UniFi-OS[false], UniFi-Cloud[false], UniFi-MongoService[false]
[2024-09-22 13:00:21,811] <launcher> INFO  system - ======================================================================
[2024-09-22 13:00:21,811] <launcher> INFO  system - BASE dir:/usr/local/share/java/unifi
[2024-09-22 13:00:21,826] <launcher> INFO  system - Current System IP: 192.168.70.1
[2024-09-22 13:00:21,827] <launcher> INFO  system - Hostname: OPNsense.localdomain
[2024-09-22 13:00:21,828] <launcher> INFO  system - ubic.env: prod
[2024-09-22 13:00:21,828] <launcher> INFO  system - System loaded
[2024-09-22 13:00:21,942] <launcher> INFO  mongo  - Checking if database needs to be shut down
[2024-09-22 13:00:23,173] <launcher> INFO  mongo  - Database was not running
[2024-09-22 13:00:23,173] <launcher> INFO  mongo  - Starting database process...
[2024-09-22 13:00:24,826] <mongo-db> WARN  mongo  - Stop listening to Mongo logs after process has exited
[2024-09-22 13:00:24,827] <mongo-db> INFO  mongo  - Database process stopped, code=62
```

**Comment by mikelock** [comment]
I have the same issue

**Comment by FRahmann** [comment]
Same here!

**Comment by mimugmail** [comment]
Sure? It should be fixed now

**Comment by FRahmann** [comment]
> Sure? It should be fixed now

Im Home in about 4 Hours. Then I can recheck and provide you some more Information

**Comment by kklyandev** [comment]
Hi, I think I have a similar issue - I can't access the Unifi controller's UI and I'm not sure where to go see logs, but I can see a bunch of "<6>pid 13181 (mongod), jid 0, uid 975: exited on signal 6 (no core dump - bad address)" messages in the General logs section on my OPNSense (version 24.7.6). 
Do you have some troubleshooting steps I could take to further diagnose the issue?

**Comment by trevorperrin** [comment]
I've got a similar issue - my opnsense firewall was inadvertently unplugged, and afterwards I couldn't access the Unifi Controller web GUI. No firewall settings were changed in between, and I'm also seeing the "exited on signal 6 (no core dump - bad address)" message in my General log.  A reboot didn't resolve it, and neither did an uninstall/reinstall.  I do have access to other services on other ports (Adguard for instance).  I'm running OPNsense 24.7.11_2 and Unifi controller WAS working before the firewall went down.

Any ideas?

**Comment by braydenhouston** [comment]
Ran into this issue as well. Power outage corrupted something about the Unifi Controller plugin. Reinstalling the plugin, restarting services, rebooting the machine all fail to fix the connection issue to the Unifi web app. I can go to the system shell and see both mongod and unifi services running.  Mongo seems to be running normally as far as I can tell. I am able to connect to it. 

I am also seeing the symptoms mentioned by pootinanny and kklyandev with the stack of unifi user sessions trying to connect. A new one spawns every few seconds when both services are up.

Version info:
OPNsense 25.1.5_5-amd64
os-unifi9-maxit (v1.4)

Anyone else have any luck with this?

**Comment by Qhilm** [comment]
I posted a (very unelegant) fix on https://github.com/mimugmail/opn-repo/issues/284: delete everything, reinstall, restore backup.
